### ISSUE TITLE
AuthorizedKeysFile

### ISSUE THREAD

**Issue by gerard-leijdekkers** [fnichol/chef-openssh#8]
It is a shame AuthorizedKeysFile can not be set in combination with PasswordAuthentication no.

That is a very common used option no?

**Comment by fnichol** [comment]
# Upstream Development Status Of The OpenSSH Chef Cookbook

Hi there.

First off, I'm sorry this reply may come extremely late (and may not even apply to anyone on this thread anymore), but I wanted to let everyone know that the canonical source for the OpenSSH Chef cookbook is maintained by [Chef Software Inc.](https://chef.io) here:

* Source code: https://github.com/chef-cookbooks/openssh
* Supermarket: https://supermarket.chef.io/cookbooks/openssh

Since this has been the case for over 2 years, I'm trying to redirect any interest and traffic there, and slowing this repository to a "redirection state". As a consequence, I'm going to close this issue out. The master branch has been left intact for the time being, but it is highly recommended to no longer link against this repository in the future.

Please direct any development, issues, and pull requests at the above GitHub repository. Thank you very much!
